
tasks:
  - init: .gitpod/init.sh # runs during prebuild
    command: task exercise # runs at start up

# List the ports to expose. Learn more https://www.gitpod.io/docs/config-ports/
ports:
  - port: 3000
    onOpen: open-preview

vscode:
  extensions:
    - bazelbuild.vscode-bazel
    - vscodevim.vim
    - golang.go
    - paulvarache.vscode-taskfile
    - .gitpod/vscode-taskfile-0.0.6.vsix
