version: 3

tasks:
  glaze:
    cmds:
      - bazel run //:gazelle
  testall:
    cmds: 
      - bazel test //...
  buildall:
    cmds: 
      - bazel build //...
  build:
    cmds:
      - bazel build {{.CLI_ARGS}}
  test:
    cmds:
      - bazel test {{.CLI_ARGS}}
  run:
    cmds:
      - bazel run {{.CLI_ARGS}}
  goget:
    cmds:
      # - go get {{.CLI_ARGS}}
      - bazel run //:gazelle -- update-repos -from_file=go.mod