version: 2

tasks:
  glaze:
    cmds:
      - bazelisk run //:gazelle
  testall:
    cmds: 
      - bazelisk test //...
    sources: 
      - "**/*"

  buildall:
    cmds: 
      - bazelisk build //...
  build:
    cmds:
      - bazelisk build {{.CLI_ARGS}}
  test:
    cmds:
      - bazelisk test {{.CLI_ARGS}}
  run:
    cmds:
      - bazelisk run {{.CLI_ARGS}}
  goget:
    cmds:
      - bazelisk run //:gazelle -- update-repos -from_file=go.mod
  exercise:
    cmds:
      - task: buildall
      - task: testall