load("@io_bazel_rules_go//go:def.bzl", "go_binary")

go_binary(
    name = "golang-test",
    srcs = ["main.go"],
    importpath = "github.com/example/project/golang-test",
    visibility = ["//visibility:public"],
)
