name: presubmit

on:
  pull_request:
    branches:
      - 'master'

jobs:
  presubmit:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up go
        uses: actions/setup-go@v1
        with:
          go-version: '^1.16'
      - name: Setup build
        run: .gitpod/setup-build.sh 
      - name: Install Task
        uses: arduino/setup-task@v1
      - name: Test all
        run: task testall