name: presubmit

on:
  pull_request:
    branches:
      - 'master'

jobs:
  presubmit:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup build
        run: .gitpod/setup-build.sh 
      - name: Test all
        run: task testall